chemin:
  dette:
    inventaire: "https://debttreasurymanagerbucket.s3.eu-central-1.amazonaws.com"
server:
  port: 5000
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://debttreasurymanager.cgoti3oxdg1y.eu-north-1.rds.amazonaws.com:3306/debttreasurymanager
    username: root
    password: mysqldatabase
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
#  profiles:
#    active: @spring.profiles.active@

